### ISSUE TITLE
missing lots of tape assertions

### ISSUE THREAD

**Issue by ljharb** [Raynos/collapsed-assert#1]
The first one I ran into was `throws`. Is there any intention to support all of tape's assertions in this library?

**Comment by Raynos** [comment]
👍 

Caveat, I’d rather not support all the aliases. But definitely at least one for each tape assertion.

I literally only use assert.equal in loops 🤣

**Comment by ljharb** [comment]
Totally fine to not have the aliases, i don't use them anyways :-)

tbf in the package i'm trying to use this in, the only things i use in loops are equal, deepEqual, and throws.

**Comment by Raynos** [comment]
Implemented in https://github.com/Raynos/collapsed-assert/pull/2
